version: "3.9"
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
  ingestor:
    build:
      context: .
      target: ingestor
    depends_on:
      - clickhouse
    env_file:
      - .env
    ports:
      - "8080:8080"
      
volumes:
  clickhouse-data:
    name: clickhouse-data